export const pricingNavConfig = [
  {
    title: 'Ücretlendirme',
    breadcrumbTitle: 'Ücretlendirme',
    path: '/pricing',
    icon: 'currency-dollar',
  },
  {
    title: 'İskonto ve Fatura Başına Ücretlendirme',
    breadcrumbTitle: 'Ürün ve Finansör Bazlı İşlem Ücreti Tanımlama',
    path: '/pricing/operation-charge-list',
    icon: 'receipt',
    hidden: true,
  },
  {
    title: 'İşlem Başı Ücretlendirme',
    breadcrumbTitle: 'İşlem Başı Ücretlendirme',
    path: '/pricing/islem-basi-ucretlendirme',
    icon: 'receipt',
    hidden: true,
  },
  {
    title: 'İşlem Başı Ücretlendirme - Yeni',
    breadcrumbTitle: 'Yeni Ücret Tanımı',
    path: '/pricing/islem-basi-ucretlendirme/yeni',
    icon: 'plus',
    hidden: true,
  },
  {
    title: 'İşlem Başı Ücretlendirme - Düzenle',
    breadcrumbTitle: 'Ücret Tanımı Düzenle',
    path: '/pricing/islem-basi-ucretlendirme/duzenle/:id',
    icon: 'edit-01',
    hidden: true,
  },
  {
    title: 'İşlem Ücreti İndirim Tanımlama',
    breadcrumbTitle: 'İşlem Ücreti İndirim Tanımlama',
    path: '/pricing/indirim-tanimlama',
    icon: 'percent-01',
    hidden: true,
  },
  {
    title: 'Web Sitesi İşlem Ücreti Baremleri',
    breadcrumbTitle: 'Web Sitesi İşlem Ücreti Baremleri',
    path: '/pricing/islem-ucreti-baremleri',
    icon: 'bar-chart-01',
    hidden: true,
  },
  {
    title: 'Web Sitesi İşlem Ücreti Baremleri - Yeni',
    breadcrumbTitle: 'Yeni Barem',
    path: '/pricing/islem-ucreti-baremleri/yeni',
    icon: 'plus',
    hidden: true,
  },
  {
    title: 'Web Sitesi İşlem Ücreti Baremleri - Düzenle',
    breadcrumbTitle: 'Barem Düzenle',
    path: '/pricing/islem-ucreti-baremleri/:id/duzenle',
    icon: 'edit-01',
    hidden: true,
  },
  {
    title: 'Operasyon Ücretlendirme',
    breadcrumbTitle: 'Operasyon Ücretlendirme',
    path: '/pricing/operasyon-ucretlendirme',
    icon: 'activity',
    hidden: true,
  },
  {
    title: 'Manuel İşlem Ücreti Ödemeleri Takibi',
    breadcrumbTitle: 'Manuel İşlem Ücreti Ödemeleri Takibi',
    path: '/pricing/manual-transaction-fee-tracking',
    icon: 'credit-card-01',
    hidden: true,
  },
  {
    title: 'Manuel İşlem Ücreti Detayı',
    breadcrumbTitle: 'İşlem Detayı',
    path: '/pricing/manual-transaction-fee-tracking/:id',
    icon: 'file-text',
    hidden: true,
  },
  {
    title: 'Manuel İşlem Ücreti Düzenle',
    breadcrumbTitle: 'İşlem Düzenle',
    path: '/pricing/manual-transaction-fee-tracking/:id/edit',
    icon: 'edit-01',
    hidden: true,
  },
];
