export const otherOperationsNavConfig = [
  {
    title: 'Diğer İşlemler',
    breadcrumbTitle: 'Diğer İşlemler',
    path: '/other-operations',
    icon: 'tool-01',
  },
  {
    title: 'Limitleri Pasife Al',
    breadcrumbTitle: 'Limitleri Pasife Al',
    path: '/toplu-islemler/limitleri-pasife-al',
    icon: 'pause-circle',
    hidden: true,
  },
  {
    title: 'Ticari Kredi Limitleri Sorgulama',
    breadcrumbTitle: 'Ticari Kredi Limitleri',
    path: '/other-operations/commercial-loan-limits',
    icon: 'search-sm',
    hidden: true,
  },
  {
    title: 'Alıcıya Tanımlı Tedarikçi Sorgusu',
    breadcrumbTitle: 'Alıcıya Tanımlı Tedarikçi Sorgusu',
    path: '/other-operations/supplier-query',
    icon: 'users-01',
    hidden: true,
  },
  {
    title: 'Spot Kredi Limitleri Sorgulama',
    breadcrumbTitle: 'Spot Kredi Limitleri',
    path: '/other-operations/spot-loan-limits',
    icon: 'trending-up-01',
    hidden: true,
  },
  {
    title: 'Revolving Kredi Limitleri Sorgulama',
    breadcrumbTitle: 'Revolving Kredi Limitleri',
    path: '/other-operations/revolving-loan-limits',
    icon: 'refresh-cw-01',
    hidden: true,
  },
  {
    title: 'TTK Limit Sorgulama',
    breadcrumbTitle: 'TTK Limit Sorgulama',
    path: '/other-operations/ttk-limit-sorgulama',
    icon: 'search-lg',
    hidden: true,
  },
];
