pool:
  name: Azure Pipelines
  vmImage: ubuntu-latest
  demands: npm
trigger:
  branches:
    include:
      - master

steps:
  - task: NodeTool@0
    inputs:
      versionSource: 'spec'
      versionSpec: '20.15.x'

  - task: Npm@1
    displayName: 'npm cache clean'
    inputs:
      command: custom
      verbose: false
      customCommand: 'cache clean --force'

  - task: Npm@1
    displayName: 'npm install'
    inputs:
      command: custom
      verbose: false
      customCommand: 'install --legacy-peer-deps'

  - task: Npm@1
    displayName: 'npm cache clean'
    inputs:
      command: custom
      verbose: false
      customCommand: 'cache clean --force'

  - task: Npm@1
    displayName: 'npm build-release'
    inputs:
      command: custom
      verbose: false
      customCommand: 'run build-release'

  - task: ArchiveFiles@2
    displayName: 'Archive dist'
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist-demo'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildNumber)/Demo.zip'
      replaceExistingArchive: true

  - task: CopyFiles@2
    displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
    inputs:
      SourceFolder: '$(Build.ArtifactStagingDirectory)/$(Build.BuildNumber)/Demo.zip'
      Contents: '**/*'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: portaldemo'
    inputs:
      ArtifactName: portaldemo
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'

  - task: ArchiveFiles@2
    displayName: 'Archive dist'
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist-production'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildNumber)/Production.zip'
      replaceExistingArchive: true

  - task: CopyFiles@2
    displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
    inputs:
      SourceFolder: '$(Build.ArtifactStagingDirectory)/$(Build.BuildNumber)/Production.zip'
      Contents: '**/*'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: portalprod'
    inputs:
      ArtifactName: portalprod
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: radarprod'
    inputs:
      ArtifactName: radarprod
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
