pool:
  name: Azure Pipelines
  vmImage: ubuntu-latest
  demands: npm
trigger:
  branches:
    include:
      - development

steps:
  - task: NodeTool@0
    inputs:
      versionSource: 'spec'
      versionSpec: '20.15.x'

  - task: Npm@1
    displayName: 'npm cache clean'
    inputs:
      command: custom
      verbose: false
      customCommand: 'cache clean --force'

  - task: Npm@1
    displayName: 'npm install'
    inputs:
      command: custom
      verbose: false
      customCommand: 'install --legacy-peer-deps'

  - task: Npm@1
    displayName: 'npm cache clean'
    inputs:
      command: custom
      verbose: false
      customCommand: 'cache clean --force'

  - task: Npm@1
    displayName: 'npm build-testt'
    inputs:
      command: custom
      verbose: false
      customCommand: 'run build-test'

  - task: ArchiveFiles@2
    displayName: 'Archive dist'
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildNumber).zip'
      replaceExistingArchive: true

  - task: CopyFiles@2
    displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
    inputs:
      SourceFolder: '$(Build.ArtifactStagingDirectory)/$(Build.BuildNumber).zip'
      Contents: '**/*'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: portaltest'
    inputs:
      ArtifactName: portaltest
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
